### PR TITLE
Corrections to main.toml in Dutch

### PR DESCRIPTION
**Pull request by Tricky1975**
Very nice of you to translate GameJolt to the Dutch language.
However I know that with THIS amount of text it was impossible to make everything error-free.
As we say in Dutch "Vier ogen zien meer dan twee" (means: Four eyes do see more than two eyes do), so I've checked and corrected main.toml
Since I'm a novel writer for the Dutch language and also work as a spelling corrector/translator from English for a foundation teaching how to use a computer, I believe I was the right person to do so. (And my old man was a teacher who also taught Dutch (aside from history and geography)) :)

To the admins I want to advice to BEFORE merging this pull request into the repository to consult the original translator as I don't want to sneak past behind his/her back.
Plus a few points are a matter of opinion, rather than facts.

Below are my motivations to make the changes I made, or a few remarks for sentences that made me doubt things a little.

Remarks/comments:
- line 32: The content had to follow up <username> "has replied to". In the original translation, this did not lead to a correct Dutch sentence
- line 48: The "thou" joke could be done in Dutch as well, and this correction did it.
- Line 68+146+169: Though "Fris" is the Dutch word for "Fresh" I got the feeling the way it is used on GameJolt is a way not really suitable in Dutch, but I left it the way it is now as I have to see the page to make sure.
- Line 138+139: Fireside notices not translated. I need to check fireside though to see what a good translation would be.
- Line 190: Converted into a way that the sentence "flows" better in Dutch
- Line 229+333+342+343+353+356+361+367+768+1796: The Dutch word for Trophies is "Trofeeën" and not "Trofeeén" (at least this error was consistent).
- Line 349: "Val de ontwikkelaar lastig!" Correct sentence, but not in this context.
- Line 403: It's "wordt" in this sentence with a "t" because of 3rd person single form, which is with all regular verbs in Dutch tribe + t.
- Line 414: "Schop onder zijn/haar hol" is a very good way to say this in popular Dutch, but the grammar in the sentence was not right. So that's why I corrected this.
- Line 460: The verb "comment" was meant in Dutch which means "Plaats commentaar" or "plaats opmerking". The latter is more common.
- Line 461+462: And that's also the reason why I changed these two lines, as for me the lines were awful to read. For me as a novel writer in Dutch, those lines hurt me ;) Plus, the word "commentaar" is in Dutch very often interpreted in a negative sense, and we do not want that, do we?
- Line 570+577: "Weerhoudt". The "t" is required as 3rd person single forum, since "weerhoudt" is tied to "iets" (something) and not "je" (you), as in the latter case the "t" would indeed have to be removed.
- Line 573: I placed this one in more correct grammar.
- Line 582: I have to look this one up as this may not be right in Dutch, however, I'll keep it this way as the best way to do it, can lead to a lot of space. "Games van deze ontwikkelaar"
- Line 606: Added "wordt" for better grammar
- Line 700: "For" was untranslated. It's "Voor" in Dutch. Corrected.
- Line 714: the dash "-" is required in Dutch for "e-mail".
- Line 820: "No Worries" is said a lot in Dutch, but wouldn't it be better to just say "Geen Zorgen" which is just more common? (I didn't correct that as I wanted to leave that one to the original translator).
- Line 853+899: You forgot to translate this one, so I did it for you. ;)
- Line 900: Maybe correct Dutch, but nobody I know uses the word "valide" in that sense. (Most people use it to say that a human being does not suffer from a (mobility) handicap, and therefore that word can be taken out of context quite easily). "Geldig" is what everybody I know uses. :)
- Line 919: Added "zelf" to give the sentence a better for and also a better understanding to a native Dutch speaker.
- Line 923: "Het is toegestaan games in ontwikkeling te plaatsen, wanneer ze gemarkeerd zijn als "In Ontwikkeling". Games in ontwikkeling moeten speelbaar zijn voordat je ze zichtbaar maakt op de site." This is a GJ rule and it says you may only show games that are playable. However I thought games that were marked as "In development" may also be shown without playable content. This would mean this line is not right. So I'm looking to you GJ staff and not to the translator, for this one. (I did not alter this line).
- Line 935: The original line is officially correct Dutch, but FNAF fans are kids, and they need simple Dutch with a wording every Dutch "boerenlul" can use. That's why I changed the line. ;)   (no offense intended with this line).
- Line 963: I leave this one to the original translator, but most Dutch people just use the English word for "Screenshot" even when they speak Dutch. They even say "Screenshotten" as a Dutchified verb for "to screenshot".
- Line 1269-1271: "Sigaretten" only refers to "cigarettes". "Tabak" and "Tabakswaar" to all tabacco products, and I think this is a very important correction as some people can be very literal and thus deem pipes and cigars not a reason to note, while in the original English setup it is.
- Line 1583: In Dutch we say "Downloadbaar" in stead of "Downloadable"
- Line 1599: Here you did use the Dutch word.... XD
- Line 1627: As I believe the word "Class" refers to a keyword in the Java programming languages I left it the way it was (as the Dutch word would be "Klasse" in this case. In the case of a class in school it's "Klas").
- Line 1662: True "Lanceren" means "To Launch" in Dutch, but only when launching something into space or when you "launch a new plan". It's never used for launching an executable file. (Some "pros" sometimes use the English word, but NEVER the Dutch word)
- Line 1815+1816+1820+1852+1863+1873+1904: Not only was "Trofeeën" misspelled, again, but it also contained an HTML error making the browser display it incorrectly. I fixed both issues here.
- Line 1837+1842: "Privé" is the correct spelling in Dutch as we copied the word directly from the French language.

At your service.

### CODE REVIEW

**Comment by hworld** [comment]
Hey, would you two be able to use the new translation system to get any of these changes in? https://poeditor.com/join/project/B4nWT6EgnD

You can discuss the changes together however you'd like.

**Comment by Fappp** [comment]
Sure CROS! I started with filling scattered empty fields.

**Comment by Fappp** [comment]
@Tricky1975 What do we do with N/A ?? NB would be wrong imho, so only suggestion I have is " - " (dash)

**Comment by Tricky1975** [comment]
"NB" is mostly used for "Nota Bene" (Dutch version of "P.S.") and not for "Niet Beschikbaar" (Not available) as I think that is what you mean, and I indeed think we need to prevent that sort of confusion. I think "-" is the best option as that is mostly used, but I shall have to look up is. I shall look into everything as soon as I finished some work on my own.

And I guess we were getting hard on CROS, since I guess he doesn't know much about the Dutch language. ;)

**Pull request closed without merging**
